version: "3.8"
services:
  db_postgres:
    container_name: PostgreSQL
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./postgres_data:/var/lib/postgresql/data
  
  system_dashboard:
    build: ./system_dashboard
    container_name: System-Dashboard
    restart: always
    depends_on:
      - db_postgres
    ports:
      - 48000:8000
    command: gunicorn -w 2 -t 60 -b 0.0.0.0:8000 app:app

volumes:
  postgres_data:
    driver: local